### ISSUE TITLE
Client targets

### ISSUE THREAD

**Issue by Shyrogan** [LeafClient/Leaf#1]
A list of the "ignored" entities by the KillAura, (ESP?)

## Every entity
- _Hearts `<=` 0 `&&` is dead_ __replaced__ with death animation check

## Players:
- Creative
- Invulnerable

## Animals
- **Tameable** ignored if they're tamed by a friend or the user

## Monsters
- **Enderman** are not screaming
- **PigZombie** are not angry

**Comment by RobinHeinstein2** [comment]
Killaura ignored: Spectator mode
Ignore entity: mushroom cow (they're infinite food farms if you have bowls)

**Comment by Shyrogan** [comment]
> 
> 
> Ignore entity: mushroom cow (they're infinite food farms if you have bowls)

Just disable animals?

**Comment by Shyrogan** [comment]
Well this is still a thing since we're back at Kotlin.
